
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const App = lazy(() => import("./pages/App.tsx"));
const DashboardPage = lazy(() => import("./pages/DashboardPage.tsx"));
const ImageGeneratorPage = lazy(() => import("./pages/ImageGeneratorPage.tsx"));
const LoginPage = lazy(() => import("./pages/LoginPage.tsx"));
const SignupPage = lazy(() => import("./pages/SignupPage.tsx"));
const VideoMakerPage = lazy(() => import("./pages/VideoMakerPage.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/", element: <App />},
	{ path: "/dashboard-page", element: <DashboardPage />},
	{ path: "/dashboardpage", element: <DashboardPage />},
	{ path: "/image-generator-page", element: <ImageGeneratorPage />},
	{ path: "/imagegeneratorpage", element: <ImageGeneratorPage />},
	{ path: "/login-page", element: <LoginPage />},
	{ path: "/loginpage", element: <LoginPage />},
	{ path: "/signup-page", element: <SignupPage />},
	{ path: "/signuppage", element: <SignupPage />},
	{ path: "/video-maker-page", element: <VideoMakerPage />},
	{ path: "/videomakerpage", element: <VideoMakerPage />},

];
